name: On review update
on:
  pull_request:
    types: [ready_for_review, review_requested, review_request_removed]
  pull_request_review:
    types: [edited, dismissed, submitted]
jobs:
  extractIssueNumber:
    name: Extract Issue Number
    runs-on: ubuntu-latest
    outputs: 
      issue-number: ${{ steps.commitMsgParser.outputs.issue-number }}
    steps:
      - name: Extract Issue Number from PR
        uses: carmenfan/extract-issue-number-from-PR-merge@v1.1
        with:
          pr: ${{ github.event.number }}
          base: staging
          github-token: ${{ secrets.GITHUB_TOKEN }}
        id: commitMsgParser

  checkMergeReady:
    name: Ensure all reviewers have approved the PR
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: haya14busa/action-cond@v1
        id: condval
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: ${{ github.event.number }}
          if_false: ${{ github.event.pull_request.number }}
      - name: Check reviews
        uses: carmenfan/all-reviewers-approved@v1.0
        with:
          pr: ${{ steps.condval.outputs.value }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

#  if someone has been assigned a reviewer -> change issue status to "awaiting approval"
  calculateStatusMessage:
    name: Work out if Awaiting Approval
    if: ${{ github.event.issue.pull_request }}
    run: | 
      case $ACTION in
        review_requested ) 
          echo "::set-output name=status::Awaiting Approval"
        opened ) 
          echo "::set-output name=status::In Progress"
        ready_for_review ) 
          echo "::set-output name=status::Awaiting Approval"
      esac
    env:
      ACTION:  ${{ github.event.action }}

  awaitingApproval:
    name: If someone has been assigned a reviewer -> change issue status to "awaiting approval"
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    needs: calculateStatusMessage
    steps:
      - name: Output status
        uses: hmarr/debug-action@v2
    
      - name: Update status
        id: update_status
        uses: github/update-project-action@v2
        with:
          github_token: ${{ secrets.PROJ_MANAGEMENT_TOKEN }}
          organization: keif-gwinn
          project_number: 1
          content_id: ${{ github.event.pull_request.self.href }}
          field: Status
          value: ${{ needs.calculateStatusMessage.outputs.status }}

  changeToInProgress:
    name: If someone has been assigned a reviewer -> change issue status to "awaiting approval"
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    needs: calculateStatusMessage
    steps:
      - name: Output status
        uses: hmarr/debug-action@v2
    
      - name: Update status
        id: update_status
        uses: github/update-project-action@v2
        with:
          github_token: ${{ secrets.PROJ_MANAGEMENT_TOKEN }}
          organization: keif-gwinn
          project_number: 1
          content_id: ${{ github.event.pull_request.self.href }}
          field: Status
          value: ${{ needs.calculateStatusMessage.outputs.status }}


# make sure we're not merging DevOps changes
  devOpsSanityCheck:
    name: Ensure that custom settings are not being merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout .azure/build-and-deploy.yaml
        uses: Bhacaz/checkout-files@v2
        with:
          files: .azure/build-and-deploy.yaml
          branch: ${{ github.head_ref || github.ref_name }}
      - name: Check to see if customHelmOverride has any APP settings
        id: customHelmOverride
        uses: mikefarah/yq@master
        with:
          cmd: if ( $(yq eval '.variables.customHelmOverride | ( contains("APP_") )' .azure/build-and-deploy.yaml) === "true" ); then echo $(yq eval '.variables.customHelmOverride' .azure/build-and-deploy.yaml); exit 1;  fi
