name: On review update
on:
  pull_request:
    types: [ready_for_review, review_requested, review_request_removed]
  pull_request_review:
    types: [edited, dismissed, submitted]
jobs:
  extractIssueNumber:
    name: Extract Issue Number
    runs-on: ubuntu-latest
    outputs: 
      issue-number: ${{ steps.commitMsgParser.outputs.issue-number }}
    steps:
      - name: Extract Issue Number from PR
        uses: carmenfan/extract-issue-number-from-PR-merge@v1.1
        with:
          pr: ${{ github.event.number }}
          base: staging
          github-token: ${{ secrets.GITHUB_TOKEN }}
        id: commitMsgParser

  checkMergeReady:
    name: Ensure all reviewers have approved the PR
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: haya14busa/action-cond@v1
        id: condval
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: ${{ github.event.number }}
          if_false: ${{ github.event.pull_request.number }}
      - name: Check reviews
        uses: carmenfan/all-reviewers-approved@v1.0
        with:
          pr: ${{ steps.condval.outputs.value }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

#  if someone has been assigned a reviewer -> change issue status to "awaiting approval"
  calculateStatusMessage:
    name: Identify status message
    runs-on: ubuntu-latest
    outputs: 
      status: ${{ steps.setStatusOutput.outputs.status }}
    steps:
      - name: Set status message from input 
        id: setStatusOutput   
        run: |
          set -ex 
          case $ACTION in
            review_requested ) 
              echo "::set-output name=status::Awaiting Approval" 
              ;;
            ready_for_review ) 
              echo "::set-output name=status::Awaiting Approval" 
              ;;
            opened ) 
              echo "::set-output name=status::In Progress" 
              ;;
            review_request_removed )
              echo "::set-output name=status::In Progress" 
              ;;            
          esac
    env:
      ACTION: ${{ github.event.action }}

  getContentID:
    name: Get the content-id
    runs-on: ubuntu-latest
    needs: extractIssueNumber
    outputs: 
      content-id: ${{ steps.getContentIdFromIssue.outputs.content-id }}
    steps:
      - name: Get Content-ID From Issue Number
        id: getContentIdFromIssue
        uses: keifgwinn/extract-content-id-from-issue-number@v1.0.3
        with:
          issue-number: "${{ needs.extractIssueNumber.outputs.issue-number }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  viewDebug:
    name: viewDebug calculateStatusMessage
    runs-on: ubuntu-latest
    needs: [ calculateStatusMessage, extractIssueNumber ]
    steps:
      - name: Output status
        uses: hmarr/debug-action@v2
    env:
      calculateStatusMessage: ${{ needs.calculateStatusMessage.outputs.status }}

  changeToAwaitingApproval:
    name: Update ticket status to Awaiting Approval
    if: needs.calculateStatusMessage.outputs.status == 'Awaiting Approval'
    runs-on: ubuntu-latest
    needs: [ calculateStatusMessage, getContentID ]
    steps:
      - name: Output status
        uses: hmarr/debug-action@v2
    
      - name: Update status
        id: update_status
        uses: github/update-project-action@v2
        with:
          github_token: ${{ secrets.PROJ_MANAGEMENT_TOKEN }}
          organization: keif-gwinn
          project_number: 1
          content_id: ${{ needs.getContentID.outputs.content-id }}
          field: Status
          value: ${{ needs.calculateStatusMessage.outputs.status }}
    env:
      calculateStatusMessage: ${{ needs.calculateStatusMessage.outputs.status }}
      content_id: ${{ needs.getContentID.outputs.content-id }}

  changeToInProgress:
    name: Update ticket status to In Progress
    if: needs.calculateStatusMessage.outputs.status == 'In Progress'
    runs-on: ubuntu-latest
    needs: [ calculateStatusMessage, getContentID ]
    steps:
      - name: Output status
        uses: hmarr/debug-action@v2
    
      - name: Update status
        id: update_status
        uses: github/update-project-action@v2
        with:
          github_token: ${{ secrets.PROJ_MANAGEMENT_TOKEN }}
          organization: keif-gwinn
          project_number: 1
          content_id: ${{ needs.getContentID.outputs.content-id }}
          field: Status
          value: ${{ needs.calculateStatusMessage.outputs.status }}

  ensureWellFormattedIssueTitle:
    runs-on: ubuntu-latest
    name: Ensure a well formatted Issue Title
    steps:
    - uses: tzkhan/pr-update-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        base-branch-regex: '[a-z\d-_.\\/]+'
        head-branch-regex: 'ISSUE_\d+'
        lowercase-branch: false
        title-template: '%headbranch% - '
        body-template: |
          This fixes [#%headbranch%](https://github.com/keif-gwinn/3drepo.io/issues/%headbranch%) by merging into '%basebranch%'
        body-update-action: 'prefix'
        body-uppercase-base-match: true

# make sure we're not merging DevOps changes
  devOpsSanityCheck:
    name: Ensure that custom settings are not being merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout .azure/build-and-deploy.yaml
        uses: Bhacaz/checkout-files@v2
        with:
          files: .azure/build-and-deploy.yaml
          branch: ${{ github.head_ref || github.ref_name }}
      - name: Check to see if customHelmOverride has any APP settings
        id: customHelmOverride
        uses: mikefarah/yq@master
        with:
          cmd: if ( $(yq eval '.variables.customHelmOverride | ( contains("APP_") )' .azure/build-and-deploy.yaml) === "true" ); then echo $(yq eval '.variables.customHelmOverride' .azure/build-and-deploy.yaml); exit 1;  fi
