name: On review update
on:
  pull_request:
    types: [review_requested, review_request_removed]
  pull_request_review:
    types: [edited, dismissed, submitted]
jobs:
  extractIssueNumber:
    name: Extract Issue Number
    runs-on: ubuntu-latest
    outputs: 
      issue-number: ${{ steps.commitMsgParser.outputs.issue-number }}
    steps:
      - name: Extract Issue Number from PR
        uses: carmenfan/extract-issue-number-from-PR-merge@v1.1
        with:
          pr: ${{ github.event.number }}
          base: staging
          github-token: ${{ secrets.GITHUB_TOKEN }}
        id: commitMsgParser

  checkMergeReady:
    name: Ensure all reviewers have approved the PR
    runs-on: ubuntu-latest
    steps:
      - uses: haya14busa/action-cond@v1
        id: condval
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: ${{ github.event.number }}
          if_false: ${{ github.event.pull_request.number }}
      - name: Check reviews
        uses: carmenfan/all-reviewers-approved@v1.0
        with:
          pr: ${{ steps.condval.outputs.value }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

#  if someone has been assigned a reviewer -> change issue status to "awaiting approval"
  awaitingApproval:
    name: If someone has been assigned a reviewer -> change issue status to "awaiting approval"
    runs-on: ubuntu-latest
    needs: extractIssueNumber
    steps:
      - name: Output status
        uses: hmarr/debug-action@v2
    
      - name: Update status
        id: update_status
        uses: github/update-project-action@v2
        with:
          github_token: ${{ secrets.PROJ_MANAGEMENT_TOKEN }}
          organization: keif-gwinn
          project_number: 1
          content_id: ${{ github.event.client_payload.command.resource.id }}
          field: Status
          value: 'Awaiting Approval' #${{ github.event.client_payload.data.status }}


# make sure we're not merging DevOps changes
  devOpsSanityCheck:
    name: Ensure that custom settings are not being merged
    runs-on: ubuntu-latest
    needs: extractIssueNumber
    steps:
      - name: Checkout files
        uses: Bhacaz/checkout-files@v2
        with:
          files: .azure/build-and-deploy.yaml
          branch: ${{ github.head_ref || github.ref_name }}
      - name: Get an entry with a variable that might contain dots or spaces
        id: customHelmOverride
        uses: mikefarah/yq@master
        with:
          cmd: if ( $(yq eval '.variables.customHelmOverride | ( contains("APP_") )' .azure/build-and-deploy.yaml) === "true" ); then echo $(yq eval '.variables.customHelmOverride' .azure/build-and-deploy.yaml); exit 1;  fi

    # - language: node_js
    #   dist: focal
    #   name: DevOps Sanity Check
    #   addons:
    #   git:
    #   submodules: false
    #   depth: 1
    #   node_js:
    #     - "14.17.1"
    #   before_install:
    #     - sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.17.2/yq_linux_amd64 ; sudo chmod +x /usr/local/bin/yq
    #   script:
    #     - if ( $(yq eval '.variables.customHelmOverride | contains("rabbitmq")' .azure/build-and-deploy.yaml) === "true" ); then echo $(yq eval '.variables.customHelmOverride' .azure/build-and-deploy.yaml); travis_terminate 1;  fi
