name: On review update
on:
  pull_request:
    types: [ready_for_review, review_requested, review_request_removed]
  pull_request_review:
    types: [edited, dismissed, submitted]
jobs:
  getPRNumber:
    name: Get Current PR Number
    runs-on: ubuntu-latest
    outputs: 
      issue-number: ${{ steps.condval.outputs.value }}
    steps:
      - uses: haya14busa/action-cond@v1
        id: condval
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: ${{ github.event.number }}
          if_false: ${{ github.event.pull_request.number }}

  getIssueNumber:
    name: Get Current Issue Number
    needs: [ getPRNumber ]
    runs-on: ubuntu-latest
    outputs: 
      issue-number: ${{ steps.commitMsgParser.outputs.issue-number }}
      content-id: ${{ steps.commitMsgParser.outputs.content-id }}
    steps:
      - name: Extract Issue Number from PR
        uses: keif-gwinn/extract-issue-number-from-PR-merge@v1
        with:
          pr: ${{ needs.getPRNumber.outputs.issue-number }}
          base: staging
          github-token: ${{ secrets.GITHUB_TOKEN }}
        id: commitMsgParser

  checkMergeReady:
    name: Ensure all reviewers have approved the PR
    runs-on: ubuntu-latest
    needs: [ getIssueNumber ]
    outputs: 
      approved: ${{ steps.checkReviews.outputs.approved }}
    steps:
      - uses: haya14busa/action-cond@v1
        id: condval
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: ${{ github.event.number }}
          if_false: ${{ github.event.pull_request.number }}
      - name: Check reviews
        id: checkReviews
        uses: keif-gwinn/all-reviewers-approved@v1.0
        with:
          pr: ${{ steps.condval.outputs.value }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update status
        if: ${{ steps.checkReviews.outputs.approved }}
        id: update_status
        uses: keif-gwinn/update-project-action@1.0.12
        with:
          github_token: ${{ secrets.PROJ_MANAGEMENT_TOKEN }}
          organization: keif-gwinn
          project_number: 1
          content_id: ${{ needs.getIssueNumber.outputs.content-id }}
          field: Status
          value: 'Done'

#  if someone has been assigned a reviewer -> change issue status to "awaiting approval"
  updateProjectTicketStatus:
    name: Update Project Ticket Status
    if: failure() # if not reviewer approved let's modify the status.
    runs-on: ubuntu-latest
    outputs: 
      content-id: ${{ needs.getIssueNumber.outputs.content-id }}
      status: ${{ steps.setStatusOutput.outputs.status }}
    needs: [ getIssueNumber, checkMergeReady ]
    steps:
      - name: Set status message from input 
        id: setStatusOutput   
        run: |
          set -ex 
          case $ACTION in
            review_requested ) 
              echo "status=Awaiting Approval" >> $GITHUB_OUTPUT
              ;;
            ready_for_review ) 
              echo "status=Awaiting Approval" >> $GITHUB_OUTPUT
              ;;
            opened )
              echo "status=In Progress" >> $GITHUB_OUTPUT
              ;;
            review_request_removed )
              echo "status=In Progress" >> $GITHUB_OUTPUT
              ;;            
          esac
        env:
          ACTION: ${{ github.event.action }}
      - name: Update status
        id: update_status
        uses: keif-gwinn/update-project-action@1.0.12
        with:
          github_token: ${{ secrets.PROJ_MANAGEMENT_TOKEN }}
          organization: keif-gwinn
          project_number: 1
          content_id: ${{ needs.getIssueNumber.outputs.content-id }}
          field: Status
          value: ${{ steps.setStatusOutput.outputs.status }}
  
  #Ensure the issue number is in the pull request title.
  ensureWellFormattedIssueTitle:
    runs-on: ubuntu-latest
    name: Ensure a well formatted Issue Title
    steps:
    - uses: keif-gwinn/pr-update-action@1.0.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        base-branch-regex: '[a-z\d-_.\\/]+'
        head-branch-regex: 'ISSUE_\d+'
        lowercase-branch: false
        title-template: '%headbranch% - '

  # make sure we're not merging DevOps changes
  devOpsSanityCheck:
    name: Ensure that custom settings are not being merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout .azure/build-and-deploy.yaml
        uses: Bhacaz/checkout-files@v2
        with:
          files: .azure/build-and-deploy.yaml
          branch: ${{ github.head_ref || github.ref_name }}
      - name: Check to see if customHelmOverride has any APP settings
        id: customHelmOverride
        uses: mikefarah/yq@master
        with:
          cmd: if ( $(yq eval '.variables.customHelmOverride | ( contains("APP_") )' .azure/build-and-deploy.yaml) === "true" ); then echo $(yq eval '.variables.customHelmOverride' .azure/build-and-deploy.yaml); exit 1;  fi

  #####################
  #  Uncomment this block to get debug information about the current variables.
  #####################
  #
  # viewDebug:
  #   name: viewDebug calculateStatusMessage
  #   runs-on: ubuntu-latest
  #   needs: [ calculateStatusMessage, getIssueNumber ]
  #   steps:
  #     - name: Output status
  #       uses: hmarr/debug-action@v2
  #   env:
  #     calculateStatusMessage: ${{ needs.calculateStatusMessage.outputs.status }}
  #     issue-number: ${{ needs.getIssueNumber.outputs.issue-number }}
  
  # getContentID:
  #   name: Extract the content-id for the related issue
  #   runs-on: ubuntu-latest
  #   needs: getIssueNumber
  #   outputs: 
  #     content-id: ${{ steps.getContentIdFromIssue.outputs.content-id }}
  #   steps:
  #     - name: Get Content-ID From Issue Number
  #       id: getContentIdFromIssue
  #       uses: keifgwinn/extract-content-id-from-issue-number@v1
  #       with:
  #         issue-number: ${{ needs.getIssueNumber.outputs.issue-number }}
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
          